# Example node config file for the designated log server node
# YAML 1.2 compliant
general:
  node_name: logserver

startup_services:
  # List of services that this node should start.
- logserver: null
